spring:
  config:
    import: optional:developer-local-properties.yaml
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
application:
  app-name: tdei-filesvc

gtfs-flex:
  gtfs-flex-container-name: gtfsflex
  upload-allowed-extensions: zip #Comma separated values
  upload-topic-name: gtfs-flex-upload
gtfs-pathways:
  gtfs-pathways-container-name: gtfspathways
  upload-allowed-extensions: zip #Comma separated values
  upload-topic-name: gtfs-pathways-upload
osw:
  osw-container-name: osw
  upload-allowed-extensions: zip #Comma separated values
  upload-topic-name: osw-upload

server:
  port: '8080'
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: File service API, This API is responsible any service related to the file operation required to be executed like uploading blob, deleting, generate downloadable links etc. This service will be exposed on Azure intranet and can be consumed by Azure intranet applications/services.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI File Service API
  version: v0.1
logging:
  level:
    root: debug
    web: debug
cloud:
  azure:
    storage:
      blob:
        account-name: tdeisamplestorage
        account-key: "${CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_KEY}"
        endpoint: "${CLOUD_AZURE_STORAGE_BLOB_ENDPOINT}"
        connection-string: "${CLOUD_AZURE_STORAGE_BLOB_CONNECTION_STRING}"
    service-bus:
      connection-string: "${CLOUD_AZURE_SERVICE_BUS_CONNECTION_STRING}"