spring:
  config:
    import: optional:developer-local-properties.yaml
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
application:
  app-name: tdei-filesvc

gtfs-flex:
  container-name: "${GTFS_FLEX_CONTAINER_NAME}"
  upload-allowed-extensions: "${GTFS_FLEX_UPLOAD_ALLOWED_EXTENSIONS}"
  upload-topic-name: "${GTFS_FLEX_UPLOAD_TOPIC_NAME}"
gtfs-pathways:
  container-name: "${GTFS_PATHWAYS_CONTAINER_NAME}"
  upload-allowed-extensions: "${GTFS_PATHWAYS_UPLOAD_ALLOWED_EXTENSIONS}"
  upload-topic-name: "${GTFS_PATHWAYS_UPLOAD_TOPIC_NAME}"
osw:
  container-name: "${OSW_CONTAINER_NAME}"
  upload-allowed-extensions: "${OSW_UPLOAD_ALLOWED_EXTENSIONS}"
  upload-topic-name: "${OSW_UPLOAD_TOPIC_NAME}"

server:
  port: '8080'
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: File service API, This API is responsible any service related to the file operation required to be executed like uploading blob, deleting, generate downloadable links etc. This service will be exposed on Azure intranet and can be consumed by Azure intranet applications/services.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI File Service API
  version: v0.1
logging:
  level:
    root: debug
    web: debug
cloud:
  azure:
    storage:
      blob:
        connection-string: "${CLOUD_AZURE_STORAGE_BLOB_CONNECTION_STRING}"
    service-bus:
      connection-string: "${CLOUD_AZURE_SERVICE_BUS_CONNECTION_STRING}"