spring:
  config:
    import: optional:developer-local-properties.yaml
application:
  app-name: tdei-filesvc

gtfs-flex:
  gtfs-flex-container-name: gtfsflex
  upload-allowed-ext: zip
gtfs-pathways:
  gtfs-pathways-container-name: gtfspathways
  upload-allowed-extensions: zip
osw:
  osw-container-name: osw
  upload-allowed-ext: zip

server:
  port: '8083'
spring-doc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    disable-swagger-default-url: 'true'
  writer-with-default-pretty-printer: 'true'
swagger:
  description: File service API, this API is responsible any service related to the file operation required to be executed like uploading blob, deleting, generate downloadable links etc. This service will be exposed on Azure intranet and can be consumed by Azure intranet applications/services.
  contact:
    name: TDEI Support
    email: placeholder_support@transequity.cs.washington.edu
    url: https://placeholder.transequity.cs.washington.edu/support
  title: TDEI File Service API
  version: v0.1
logging:
  level:
    root: debug
    web: debug
cloud:
  azure:
    storage:
      blob:
        account-name: tdeisamplestorage
        account-key:
        endpoint: https://tdeisamplestorage.blob.core.windows.net/
        connection-string: